#resolver: lts-16.15
#resolver: lts-16.23
#resolver: lts-17.4
resolver: lts-17.6
packages:
- .
# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
